# file.pp - 2014-02-17 03:28
#
# Copyright (c) 2014 Paul Houghton <paul4hough@gmail.com>
#
define bacula::device::file (
  $device = undef,
  $type = undef,
  $media_type = 'File',
  $label_media = 'Yes',
  $auto_chg = undef,
  $chg_dev = undef,
  $chd_cmd = undef,
  $alert_cmd = undef,
  $drv_idx = undef,
  $auto_select = undef,
  $max_chg_wait = undef,
  $max_rw_wait = undef,
  $max_open_wait = undef,
  $always_open = 'No',
  $vol_poll = undef,
  $close_poll = undef,
  $removable = 'No',
  $random = 'Yes',
  $req_mount = undef,
  $auto_mount = undef,
  $mnt_point = undef,
  $mnt_cmd = undef,
  $umnt_cmd = undef,
  $min_blk_size = undef,
  $max_blk_size = undef,
  $heom = undef,
  $ffspace = undef,
  $mtioc = undef,
  $bsf_eom = undef,
  $two_eof = undef,
  $bsr = undef,
  $bsf = undef,
  $fsr = undef,
  $fsf = undef,
  $offline = undef,
  $max_jobs = undef,
  $max_vol_size = undef,
  $max_file_size = undef,
  $blocking = undef,
  $max_net_buf = undef,
  $max_spool = undef,
  $max_job_spool = undef,
  $spool_dir = undef,
  $max_part = undef,
  $template  = 'bacula/device.conf.erb',
  ) {
  bacula::device { "$title" :
    name  => $name ,
    device => $device,
    type => $type,
    media_type => $media_type,
    label_media => $label_media,
    auto_chg => $auto_chg,
    chg_dev => $chg_dev,
    chd_cmd => $chd_cmd,
    alert_cmd => $alert_cmd,
    drv_idx => $drv_idx,
    auto_select => $auto_select,
    max_chg_wait => $max_chg_wait,
    max_rw_wait => $max_rw_wait,
    max_open_wait => $max_open_wait,
    always_open => $always_open,
    vol_poll => $vol_poll,
    close_poll => $close_poll,
    removable => $removable,
    random => $random,
    req_mount => $req_mount,
    auto_mount => $auto_mount,
    mnt_point => $mnt_point,
    mnt_cmd => $mnt_cmd,
    umnt_cmd => $umnt_cmd,
    min_blk_size => $min_blk_size,
    max_blk_size => $max_blk_size,
    heom => $heom,
    ffspace => $ffspace,
    mtioc => $mtioc,
    bsf_eom => $bsf_eom,
    two_eof => $two_eof,
    bsr => $bsr,
    bsf => $bsf,
    fsr => $fsr,
    fsf => $fsf,
    offline => $offline,
    max_jobs => $max_jobs,
    max_vol_size => $max_vol_size,
    max_file_size => $max_file_size,
    blocking => $blocking,
    max_net_buf => $max_net_buf,
    max_spool => $max_spool,
    max_job_spool => $max_job_spool,
    spool_dir => $spool_dir,
    max_part => $max_part,
    template  => $template ,
  }
}
  
